2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten] MongoDB starting : pid=47118 port=22222 dbpath=mongo/cgn.db/db/ 64-bit host=titan-ext1
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten] db version v3.2.21
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten] git version: 1ab1010737145ba3761318508ff65ba74dfe8155
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten] allocator: tcmalloc
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten] modules: none
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten] build environment:
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten]     distarch: x86_64
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2019-02-21T13:23:03.347-0500 I CONTROL  [initandlisten] options: { config: "mongo/cgn.db/db.cfg", net: { bindIp: "0.0.0.0", port: 22222, unixDomainSocket: { pathPrefix: "mongo/cgn.db/socket" } }, storage: { dbPath: "mongo/cgn.db/db/" } }
2019-02-21T13:23:03.368-0500 I -        [initandlisten] Detected data files in mongo/cgn.db/db/ created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-02-21T13:23:03.369-0500 W -        [initandlisten] Detected unclean shutdown - mongo/cgn.db/db/mongod.lock is not empty.
2019-02-21T13:23:03.370-0500 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2019-02-21T13:23:03.370-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=150G,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
2019-02-21T13:23:04.239-0500 I STORAGE  [initandlisten] WiredTiger [1550773384:239938][47118:0x2ba428cbe5e0], txn-recover: Main recovery loop: starting at 14/379776
2019-02-21T13:23:04.241-0500 I STORAGE  [initandlisten] WiredTiger [1550773384:241749][47118:0x2ba428cbe5e0], txn-recover: Recovering log 14 through 15
2019-02-21T13:23:04.259-0500 I STORAGE  [initandlisten] WiredTiger [1550773384:259093][47118:0x2ba428cbe5e0], file:sizeStorer.wt, txn-recover: Recovering log 15 through 15
2019-02-21T13:23:05.926-0500 I CONTROL  [initandlisten] 
2019-02-21T13:23:05.926-0500 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2019-02-21T13:23:05.926-0500 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-02-21T13:23:05.926-0500 I CONTROL  [initandlisten] 
2019-02-21T13:23:05.926-0500 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2019-02-21T13:23:05.926-0500 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2019-02-21T13:23:05.926-0500 I CONTROL  [initandlisten] 
2019-02-21T13:23:05.940-0500 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
2019-02-21T13:23:05.940-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory 'mongo/cgn.db/db/diagnostic.data'
2019-02-21T13:23:05.940-0500 I NETWORK  [initandlisten] waiting for connections on port 22222
2019-02-21T13:23:06.016-0500 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2019-02-21T13:23:15.362-0500 I NETWORK  [initandlisten] connection accepted from 160.91.205.198:40778 #1 (1 connection now open)
2019-02-21T13:23:15.363-0500 I NETWORK  [conn1] received client metadata from 160.91.205.198:40778 conn1: { driver: { name: "PyMongo", version: "3.7.2" }, os: { type: "Linux", name: "SUSE Linux Enterprise Server  11 x86_64", architecture: "x86_64", version: "3.0.101-0.47.106.29-default" }, platform: "CPython 2.7.9.final.0" }
2019-02-21T13:23:15.366-0500 I NETWORK  [initandlisten] connection accepted from 160.91.205.198:40779 #2 (2 connections now open)
2019-02-21T13:23:15.366-0500 I NETWORK  [conn2] received client metadata from 160.91.205.198:40779 conn2: { driver: { name: "PyMongo", version: "3.7.2" }, os: { type: "Linux", name: "SUSE Linux Enterprise Server  11 x86_64", architecture: "x86_64", version: "3.0.101-0.47.106.29-default" }, platform: "CPython 2.7.9.final.0" }
2019-02-21T13:23:15.367-0500 I NETWORK  [conn1] end connection 160.91.205.198:40778 (1 connection now open)
2019-02-21T13:23:15.369-0500 I NETWORK  [conn2] end connection 160.91.205.198:40779 (0 connections now open)
2019-02-21T13:23:15.371-0500 I NETWORK  [initandlisten] connection accepted from 160.91.205.198:40780 #3 (1 connection now open)
2019-02-21T13:23:15.372-0500 I NETWORK  [conn3] received client metadata from 160.91.205.198:40780 conn3: { driver: { name: "PyMongo", version: "3.7.2" }, os: { type: "Linux", name: "SUSE Linux Enterprise Server  11 x86_64", architecture: "x86_64", version: "3.0.101-0.47.106.29-default" }, platform: "CPython 2.7.9.final.0" }
2019-02-21T13:23:15.373-0500 I NETWORK  [initandlisten] connection accepted from 160.91.205.198:40781 #4 (2 connections now open)
2019-02-21T13:23:15.373-0500 I NETWORK  [conn4] received client metadata from 160.91.205.198:40781 conn4: { driver: { name: "PyMongo", version: "3.7.2" }, os: { type: "Linux", name: "SUSE Linux Enterprise Server  11 x86_64", architecture: "x86_64", version: "3.0.101-0.47.106.29-default" }, platform: "CPython 2.7.9.final.0" }
2019-02-21T13:23:15.897-0500 I NETWORK  [conn3] end connection 160.91.205.198:40780 (1 connection now open)
2019-02-21T13:23:15.898-0500 I NETWORK  [conn4] end connection 160.91.205.198:40781 (0 connections now open)
2019-02-21T13:23:16.376-0500 I NETWORK  [initandlisten] connection accepted from 160.91.205.198:40783 #5 (1 connection now open)
2019-02-21T13:23:16.376-0500 I NETWORK  [conn5] received client metadata from 160.91.205.198:40783 conn5: { driver: { name: "PyMongo", version: "3.7.2" }, os: { type: "Linux", name: "SUSE Linux Enterprise Server  11 x86_64", architecture: "x86_64", version: "3.0.101-0.47.106.29-default" }, platform: "CPython 2.7.9.final.0" }
2019-02-21T13:23:16.398-0500 I NETWORK  [initandlisten] connection accepted from 160.91.205.198:40784 #6 (2 connections now open)
2019-02-21T13:23:16.399-0500 I NETWORK  [conn6] received client metadata from 160.91.205.198:40784 conn6: { driver: { name: "PyMongo", version: "3.7.2" }, os: { type: "Linux", name: "SUSE Linux Enterprise Server  11 x86_64", architecture: "x86_64", version: "3.0.101-0.47.106.29-default" }, platform: "CPython 2.7.9.final.0" }
2019-02-21T13:23:16.951-0500 I NETWORK  [conn5] end connection 160.91.205.198:40783 (1 connection now open)
2019-02-21T13:23:16.952-0500 I NETWORK  [conn6] end connection 160.91.205.198:40784 (0 connections now open)
2019-02-21T13:23:16.953-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
2019-02-21T13:23:16.953-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2019-02-21T13:23:16.956-0500 I CONTROL  [signalProcessingThread] now exiting
2019-02-21T13:23:16.956-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2019-02-21T13:23:16.956-0500 I NETWORK  [signalProcessingThread] closing listening socket: 5
2019-02-21T13:23:16.956-0500 I NETWORK  [signalProcessingThread] closing listening socket: 6
2019-02-21T13:23:16.956-0500 I NETWORK  [signalProcessingThread] removing socket file: mongo/cgn.db/socket/mongodb-22222.sock
2019-02-21T13:23:16.957-0500 I NETWORK  [signalProcessingThread] shutdown: going to flush diaglog...
2019-02-21T13:23:16.957-0500 I NETWORK  [signalProcessingThread] shutdown: going to close sockets...
2019-02-21T13:23:16.957-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2019-02-21T13:23:17.071-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2019-02-21T13:23:17.072-0500 I CONTROL  [signalProcessingThread] dbexit:  rc: 0
